### PR TITLE
Fixes actions payload continuously appending 

### LINKED ISSUE #697: Continuous Updateauth Data Growth with Live Updates Enabled on OBE Testnet Explorer Account or Tx View
# Describe the bug
On the OBE testnet explorer, when viewing the tf account or a specific transaction with live updates enabled, the updateauth dropdown data keeps growing with each automatic refresh.

# To Reproduce

Go to the tf account on the OBE testnet explorer: https://explorer-test.telos.net/account/tf
Ensure that live updates are enabled
Observe the updateauth data continuously growing with each refresh
Alternatively, view a specific transaction directly, such as: https://explorer-test.telos.net/transaction/9398eb3fd65179086d2cb571a82299fe16ac545a4724952f3d4dc8f1dd53fcac
Observe the same continuous growth of updateauth data
# Expected behavior
The updateauth data should remain consistent and not grow with each refresh when live updates are enabled.

### PR DESCRIPTION
**Pull request by karynemayer**
# Fixes #697 

## Description

This PR fixes the issue where the content of an action is continuously appended to the table with the following changes:

1. Custom check to identify if the data is the same as received in the previous request
    **Why?** The request answer _sometimes_ includes keys that are empty and sometimes it doesn't. The diff below illustrates the difference between the request payloads. Fun fact, they also change the order of the attributes, which is not depicted in the example below.
   **How?** We recursively compare the each key since we can't predict the kind of data it will be. We ignore any key that has zero content in the comparison, so the objects are considered the same.
``` diff
 {
        "data": {
            "permission": "active",
            "parent": "owner",
            "auth": {
                "threshold": 2,
-
+              "keys": [],
                "accounts": [
                  {
                      "permission": {
                          "actor": "captaincrypt",
                          "permission": "active"
                      },
                      "weight": 1
                  },
              ],
-            
+           "waits": [],
          },
          "account": "tf"
      }
  },
```

2. Created a new component responsible for showing the payload
    **Why?** Due to the complexity of the data that can come from the blockchain actions, a new component with the sole purpose of showing this data was created. It leverages recursion because of the lack of predictability on the JSON that comes from the endpoints and makes sure we show a simplified, indented version of the content.

Note that we don't print the information again if it was deemed equal to the previous one. 

## Test scenarios
Tested on the following transactions:

- The original one : `/transaction/9398eb3fd65179086d2cb571a82299fe16ac545a4724952f3d4dc8f1dd53fcac`
-  `/transaction/cb0bc295eab73a01b931463e57f932774a59cddc804acab5e28112845ea4b2d1`
- `/transaction/e058a43cf19d2f736d60cddc046329b179d04fab5121eacce14db7f4db043341` Note that the `content` key issue will be addressed in another PR/issue
- `/account/eosio.evm`

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages
-   [ ] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [x] I have tested for mobile functionality and responsiveness
-   [ ] I have added appropriate test coverage

### CODE REVIEW

File: src/components/transaction/DataFormat.vue [hunk 1]
```diff
@@ -21,46 +22,57 @@ export default defineComponent({
...
-                            dict = dict.concat(keyValArray);
-                        }
-                    } else {
-                        var keyValArray: any[] = [];
-                        let formatData = formatGeneralData(data[key]);
-                        if (formatData.length > 0) {
-                            keyValArray = keyValArray.concat(formatGeneralData(data[key]));
-                            dict = dict.concat(keyValArray);
-                        }
+                if (objectOne[key] !== null && typeof objectOne[key] === 'object') {
```
Comment (donnyquixotic) [inline src/components/transaction/DataFormat.vue:56]:
```suggestion
                if (typeof objectOne[key] === 'object') {
```
the first condition is redundant and covered by line 45 (never reaches this code if it _is_ `null`)

**Review by donnyquixotic — CHANGES_REQUESTED** [review]

File: src/components/transaction/DataFormat.vue [hunk 2]
```diff
@@ -21,46 +22,57 @@ export default defineComponent({
...
+                    if (!compareJsonObjects(objectOne[key], objectTwo[key])) {
```
Comment (donnyquixotic) [inline src/components/transaction/DataFormat.vue:57]:
```suggestion
```
condition added above

File: src/components/transaction/DataFormat.vue [hunk 3]
```diff
@@ -21,46 +22,57 @@ export default defineComponent({
...
+                        return false;
                     }
```
Comment (donnyquixotic) [inline src/components/transaction/DataFormat.vue:59]:
```suggestion
```
if statement removed above

File: src/components/transaction/DataFormat.vue [hunk 4]
```diff
@@ -21,46 +22,57 @@ export default defineComponent({
...
                 } else {
```
Comment (donnyquixotic) [inline src/components/transaction/DataFormat.vue:60]:
```suggestion
                } 
```
can remove nested statement

File: src/components/transaction/DataFormat.vue [hunk 5]
```diff
@@ -21,46 +22,57 @@ export default defineComponent({
...
-                    dict.push({ key, value: data[key] });
+                    if (objectOne[key] !== objectTwo[key]) {
+                        return false;
+                    }
```
Comment (donnyquixotic) [inline src/components/transaction/DataFormat.vue:63]:
```suggestion
```
nested if removed

File: src/components/transaction/DataFormat.vue [hunk 6]
```diff
@@ -21,46 +22,57 @@ export default defineComponent({
...
-                            keyValArray = keyValArray.concat(formatGeneralData(data[key]));
-                            dict = dict.concat(keyValArray);
-                        }
+                if (objectOne[key] !== null && typeof objectOne[key] === 'object') {
+                    if (!compareJsonObjects(objectOne[key], objectTwo[key])) {
+                        return false;
                     }
                 } else {
-                    dict.push({ key, value: data[key] });
+                    if (objectOne[key] !== objectTwo[key]) {
```
Comment (donnyquixotic) [inline src/components/transaction/DataFormat.vue:61]:
```suggestion
```
nested if removed

File: src/components/transaction/DataFormat.vue [hunk 7]
```diff
@@ -21,46 +22,57 @@ export default defineComponent({
...
+                        return false;
```
Comment (donnyquixotic) [inline src/components/transaction/DataFormat.vue:62]:
```suggestion
                    return false;
```
adjust indention

File: src/components/transaction/DataFormat.vue [hunk 8]
```diff
@@ -103,32 +115,41 @@ export default defineComponent({
...
-    <div class="col-12"><span class="text-bold">
-        <AccountFormat :account="transferData.from" type="account"></AccountFormat></span><span class="text-bold">&nbsp; → &nbsp;
-        <AccountFormat :account="transferData.to" type="account">&nbsp;</AccountFormat></span><span class="text-bold">{{ ' ' + transferData.quantity}}</span></div>
-    <div class="col-12">
-      <div class="text-weight-bold">memo:&nbsp;<span class="text-weight-regular" v-if="transferData.memo">{{transferData.memo}}</span><span class="text-weight-regular" v-else>n/a</span></div>
+<div
+    class="relative-position"
+    :class="showOverflow ? '' : 'overflow-hidden'"
+    :style="showOverflow || !isOverflowing ? '' : `max-height: calc(${maxHeight}px - ${switchHeight}px)`"
+>
```
Comment (donnyquixotic) [inline src/components/transaction/DataFormat.vue:128]: change in-line styling to a conditional class `:class=""{ overflow-height-class: !showOverflow && isOverflowing }"`

where (named arbitrarily for example) 
`.overflow-height-class {
      max-height: 37px //the calc values are hard-coded so don't need the variables
}`

File: src/components/transaction/DataFormat.vue [hunk 9]
```diff
@@ -21,46 +22,57 @@ export default defineComponent({
         },
     },
     setup(props) {
-        const { actionName, actionData, useColor } = toRefs(props);
-        const dataBox = ref(null);
+        const { actionName, actionData } = toRefs(props);
+        const dataBox = ref<null | HTMLElement>(null);
         const showOverflow = ref(false);
         const maxHeight = ref(57);
         const switchHeight = ref(20);
```
Comment (donnyquixotic) [inline src/components/transaction/DataFormat.vue:29]:
```suggestion
```
unnec var see line 127

File: src/components/transaction/DataFormat.vue [hunk 10]
```diff
@@ -21,46 +22,57 @@ export default defineComponent({
         },
     },
     setup(props) {
-        const { actionName, actionData, useColor } = toRefs(props);
-        const dataBox = ref(null);
+        const { actionName, actionData } = toRefs(props);
+        const dataBox = ref<null | HTMLElement>(null);
         const showOverflow = ref(false);
         const maxHeight = ref(57);
```
Comment (donnyquixotic) [inline src/components/transaction/DataFormat.vue:28]:
```suggestion
```
unnec var see line 127

**Review by donnyquixotic — CHANGES_REQUESTED** [review]

File: src/components/transaction/DataFormat.vue (hunk 9 above)
Comment (donnyquixotic) [inline src/components/transaction/DataFormat.vue:29]:
```suggestion
```
unnec var see line 127

**Review by donnyquixotic — CHANGES_REQUESTED** [review]

File: src/components/transaction/DataFormat.vue (hunk 1 above)
Comment (karynemayer) [reply src/components/transaction/DataFormat.vue:56]: I would rather we just remove the redundant condition. Including `!compareJsonObjects(objectOne[key], objectTwo[key])) || objectOne[key] !== objectTwo[key]` would make `compareJsonObjects` to be called every time, even when `objectOne[key]` is not an `object`.
We could change the order to avoid that, putting `objectOne[key] !== objectTwo[key]` comparison first, but I still feel that it just makes it harder to read. 

Would you be okay with this?

```
if (typeof objectOne[key] === 'object') {
    if (!compareJsonObjects(objectOne[key], objectTwo[key])) {
        return false;
    }
} else {
    if (objectOne[key] !== objectTwo[key]) {
        return false;
    }
}
```

Comment (donnyquixotic) [reply src/components/transaction/DataFormat.vue:56]: No, if that first condition itsn't met, it will short circuit and not evaluate the `compareObjects()` method

File: src/components/transaction/DataFormat.vue [hunk 11]
```diff
@@ -21,50 +22,63 @@ export default defineComponent({
...
         const showOverflow = ref(false);
-        const maxHeight = ref(57);
-        const switchHeight = ref(20);
         const isOverflowing = ref(false);
         const transferData = computed(() => actionData.value as TransferData);
         const clientHeight = computed(() => dataBox.value?.clientHeight ?? 0);
+        let currentData = ref<string | unknown>(null);
+        const maxHeight = 57; // the maximum row height
+        const switchHeight = 20;
+        const maxHeightStyle = computed(() =>
```
Comment (donnyquixotic) [inline src/components/transaction/DataFormat.vue:34]: this doesn't need to be computed since the values don't change or need to be reactive. optionally you could remove the `switchHeight` variable which isn't used elsewhere and just have `const maxHeightStyle = 37px // comment` whichever you prefer for readability.
```suggestion
        const maxHeightStyle = `calc(${maxHeight}px - ${switchHeight}px)`;
```

File: src/components/transaction/DataFormat.vue [hunk 12]
```diff
@@ -101,34 +115,41 @@ export default defineComponent({
...
-<div class="relative-position" :class="showOverflow ? '' : 'overflow-hidden'" :style=" (showOverflow || !isOverflowing) ? '' : `max-height: calc(${maxHeight}px - ${switchHeight}px)`">
-  <div class="row" v-if="actionName === 'transfer'" ref="dataBox">
-    <div class="col-12"><span class="text-bold">
-        <AccountFormat :account="transferData.from" type="account"></AccountFormat></span><span class="text-bold">&nbsp; → &nbsp;
-        <AccountFormat :account="transferData.to" type="account">&nbsp;</AccountFormat></span><span class="text-bold">{{ ' ' + transferData.quantity}}</span></div>
-    <div class="col-12">
-      <div class="text-weight-bold">memo:&nbsp;<span class="text-weight-regular" v-if="transferData.memo">{{transferData.memo}}</span><span class="text-weight-regular" v-else>n/a</span></div>
+<div
+    class="relative-position"
+    :class="{'overflow-hidden': !showOverflow, 'div-compressed': !showOverflow}"
```
Comment (donnyquixotic) [inline src/components/transaction/DataFormat.vue:127]: double-check this but I believe the quasar class `overflow-hidden` is redundant now due to `div-compressed` (doesn't appear to do anything when disabled in dev tools)
```suggestion
    :class="{ 'div-compressed': !showOverflow }"
```

File: src/components/transaction/DataFormat.vue [hunk 13]
```diff
@@ -101,34 +115,41 @@ export default defineComponent({
...
+            </div>
+        </div>
     </div>
-  </div>
-  <div class="row" v-else ref="dataBox">
-    <div class="col-12" v-for="val in formatGeneralData(data)" :key="val.key">
-      <div class="text-weight-bold">{{val.key}} :<span class="text-weight-regular" v-if="isAccount(val.key)">
-          <AccountFormat :account="val.value" type="account">&nbsp;</AccountFormat></span><span class="text-weight-regular" v-else>{{val.value}} &nbsp;</span></div>
+    <div v-else ref="dataBox" class="row">
+        <PrettyPayload :depth="0" :payload="formatGeneralData(actionData)"/>
```
Comment (donnyquixotic) [inline src/components/transaction/DataFormat.vue:142]: If you look in console you see a bunch of `runtime-core.esm-bundler.js:38 [Vue warn]: Invalid prop: type check failed for prop "payload". Expected Object, got Null  
  at <PrettyPayload depth=2 payload=null > ` warnings. This is because the payload property for the `PrettyPayload` component is null in some cases. Updating `payload` property in src/components/transaction/PrettyPayload.vue to accept null as an optional type should resolve those e.g. `payload: { type: Object || null, required: true },
`

**Review by donnyquixotic — CHANGES_REQUESTED** [review]

**Review by donnyquixotic — APPROVED** [review]
