### PR TITLE
138 bug single transaction view incomplete

### LINKED ISSUE #138: BUG - Single transaction view incomplete
As implemented:
image

As designed:
image

Missing:
- The entire top block is missing
- Tabs are missing
- Trace is missing
- RAW is missing

### PR DESCRIPTION
**Pull request by WikusKriek**
# Pull Request Template

## Description

Transaction view info and tabs with action, traces and raw view.

Fixes #138 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by WikusKriek** [comment]
@DonaldPeat this is done now if you want to take a look.

File: src/components/Header.vue [hunk 1]
```diff
@@ -148,47 +148,49 @@ export default defineComponent({
...
+            fill-input
+            input-debounce="0"
+            :options="options"
+            @update="executeSearch"
+            @keyup.enter="executeSearch" 
+            :input-style="{ color: 'white' }"
+            @click="executeSearch"
+            @input-value="getOptions")
+              template( v-slot:option="scope")
+                q-item(v-if="!scope.opt.groupLabel"
```
Comment (DonaldPeat) [inline src/components/Header.vue:178]: you can re-order `q-item` s here for most likely case first as` v-if=<condition>`  and second as `v-else`

File: src/components/Transaction/TransactionCard.vue [hunk 2]
```diff
@@ -0,0 +1,132 @@
...
+        q-card-section.q-pl-md
+          div(class="text-h4 text-bold") Transaction
+        
+        q-card-section.q-pt-none
+          .row.items-center
+            .col-11.text-bold.ellipsis {{transaction}}
+            .col-1
+              q-btn.float-right( @click="copy(transaction)" flat round color="black" icon="content_copy" size='sm')
+        //- q-card-section.q-pt-none
+        //-   q-btn.button-primary( @click="copyTransactionId" flat label="MSIG Template")
```
Comment (DonaldPeat) [inline src/components/Transaction/TransactionCard.vue:75]: remove unless it is a placeholder for future functionality

**Review by DonaldPeat — CHANGES_REQUESTED** [review]

File: src/components/Transaction/TransactionCard.vue (hunk 2 above)
Comment (WikusKriek) [reply src/components/Transaction/TransactionCard.vue:75]: Yes I guess we will have the MSIG sometime in near future so this will be used then.

File: src/components/Header.vue (hunk 1 above)
Comment (WikusKriek) [reply src/components/Header.vue:178]: Do you mean have a localstorage entry that saves past searches and order those on top?

**Review by DonaldPeat — APPROVED** [review]
