### PR TITLE
Fixing landing page on single chain mode

### LINKED ISSUE #766: Disable landing page for single chain mode
When you are in single chain mode, without the dropdown enabled, you should never see the landing page.

### PR DESCRIPTION
**Pull request by jaegerfe**
# Fixes #766 #767 

## Description

Disabling landing page on single-chain mode.
Includes fix for validation of `SHOW_MULTICHAIN_SELECTOR` that is a `string` and was being considered a `boolean`.

## Test scenarios
- Make sure `SHOW_MULTICHAIN_SELECTOR` is `false`
- Make sure you have `CHAIN_NAME` set to the desired network
- Navigate through the website without ever seeing the home page

## Checklist:

-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have cleaned up the code in the areas my change touches
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have removed any unnecessary console messages
-   [ ] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [ ] I have tested for mobile functionality and responsiveness
-   [ ] I have added appropriate test coverage

### CODE REVIEW

File: src/router/index.ts [hunk 1]
```diff
@@ -42,6 +42,14 @@ export default route<StateInterface>(function (/* { store, ssrContext } */) {
...
         if (to.path === '/') { // if attempting to go to home page
+            if (process.env.SHOW_MULTICHAIN_SELECTOR !== 'true') {
+                return({
+                    path: 'network',
+                    query: {
+                        network: process.env.CHAIN_NAME,
+                    },
+                });
+            }
             if (to.query.network) { // if there is network param, proceed to network with the param
```
Comment (donnyquixotic) [inline src/router/index.ts:53]: @jaegerfe If multichain selector is set to false, it will never reach network param logic, is this the intended behavior or just a temporary fix?

**Review by donnyquixotic — CHANGES_REQUESTED** [review]

File: src/router/index.ts (hunk 1 above)
Comment (karynemayer) [reply src/router/index.ts]: @donnyquixotic Yes, it was supposed to be a quick and dirty fix :)
I added a new commit that I believe addresses both #766 and #767. Please, double check and let me know!

@jaegerfe it would be awesome if you could also review it ❤️

**Review by donnyquixotic — APPROVED** [review]

File: src/router/index.ts (hunk 1 above)
Comment (karynemayer) [reply src/router/index.ts]: @donnyquixotic I’ve updated the PR once again - and I believe this is the last time. Eduardo pointed that I had left some unreachable condition, so I just removed that for now.

Also added @poplexity as a reviewer since it doesn't make sense that I approve my own changes.

**Review by poplexity — APPROVED** [review]
Looks good to me! 👍

**Review by Viterbo — CHANGES_REQUESTED** [review]
It does not accomplish everything requested in #767:
"in fact, we should probably remove them "...(not used params)..." if they are there (even if they are wrong)"

If you go to http://localhost:8080/network?network=eos it keeps the "wrong" parameter when it should be removed.

**Review by donnyquixotic — APPROVED** [review]

**Comment by donnyquixotic** [comment]
> Good work, although It does not accomplish everything requested in #767: "in fact, we should probably remove them "...(not used params)..." if they are there (even if they are wrong)"
> 
> If you go to http://localhost:8080/network?network=eos it keeps the "wrong" parameter when it should be removed.

Good catch & valid point. Seeing as it's not an organic user flow to and will be handled as part of the larger multi-chain effort, we won't worry about this for now.

**Review by donnyquixotic — APPROVED** [review]
