### PR TITLE
unstake and savings available inputs displaying incorrect value

### LINKED ISSUE #708: 'unstake' and 'savings' available inputs displaying incorrect value
**Describe the bug**
The available amounts displayed (and populated on click) for savings and unstake are incorrect and should reflect matured balance.

**To Reproduce**
1. Login to explorer with an account that has a matured REX balance
2. Click on 'Wallet' 
3. Click on 'Staking (REX)'
4. Select 'Unstake' tab, see incorrect value displayed above input (matured TLOS)
5. Select 'Savings' tab, see incorrect value displayed above input (stake to savings)

**Expected behavior**
Value should reflect matured TLOS balance

**Additional context**
Seems like the values _may_ be 'correct' and just be off by a few orders of magnitude (e.g. 123,456.7890 displayed as 123.)

### PR DESCRIPTION
**Pull request by donnyquixotic**
# Fixes #708

## Description
See issue description

## Test scenarios
See issue for testing steps

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages
-   [x] I have added appropriate test coverage

### CODE REVIEW

File: src/utils/string-utils.ts [hunk 1]
```diff
@@ -69,12 +69,16 @@ export function formatCurrency(
...
-        return parseFloat(qty);
+        return parseFloat(qty.replace(/,/g, '')); // remove commas
     } catch (error) {
         return 0;
     }
 }
 
+export function formatNumberWithCommas(num: number): string {
+    return num.toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ',');
+}
```
Comment (Viterbo) [inline src/utils/string-utils.ts:80]: I learned with @EJSG that you can delegate this number-formating job to the javascript built-in solution Intl.NumberFormat like this:

```suggestion
export function formatNumberWithCommas(num: number): string {
  return new Intl.NumberFormat('en-US', {
    minimumFractionDigits: 0,
    maximumFractionDigits: 20,
  }).format(num);
}
```

**Review by Viterbo — APPROVED** [review]

**Review by EJSG — APPROVED** [review]
