### PR TITLE
Debounce header search input

### LINKED ISSUE #813: Need debounce for search to prevent incorrect results
**Describe the bug**
The search feature appears to re-refetch on every keystroke. Sometimes the 2nd-to-last response arrives last and displays results that do not match with the current value of the text input. A debounce should fix this.

**To Reproduce**
1. Go to search
2. Type in `eosio` quickly
3. Sometimes the dropdown results will not match the `eosio` input

**Expected behavior**
No re-fetch until the search input goes ~300 milliseconds without another key press

**Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by kylanhurt**
# Fixes #813 

## Description

Added a debounce utility function and implemented it for header search

## Test scenarios

Start typing into header

## Checklist:

-   [X] I have performed a self-review of my own code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] I have cleaned up the code in the areas my change touches
-   [X] My changes generate no new warnings
-   [X] Any dependent changes have been merged and published in downstream modules
-   [X] I have checked my code and corrected any misspellings
-   [X] I have removed any unnecessary console messages
-   [X] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [X] I have tested for mobile functionality and responsiveness
-   [X] I have added appropriate test coverage

### CODE REVIEW

File: src/utils/time.ts [hunk 1]
```diff
@@ -0,0 +1,19 @@
+export function sleep(timeout = 1000): Promise<void> {
+    return new Promise(r => setTimeout(r, timeout));
+}
+
+// eslint-disable-next-line @typescript-eslint/no-explicit-any
+export const debounce = <T extends (...args: any[]) => ReturnType<T>>(
+    callback: T,
+    timeout: number,
+): ((...args: Parameters<T>) => void) => {
+    console.log('debouncing');
```
Comment (donnyquixotic) [inline src/utils/time.ts:10]:
```suggestion
```

File: src/components/HeaderSearch.vue [hunk 2]
```diff
@@ -34,7 +35,11 @@ export default defineComponent({
             });
 
             isLoading.value = false;
-        });
+        };
+
+        const onInput = debounce(fetchData, 400);
```
Comment (donnyquixotic) [inline src/components/HeaderSearch.vue:40]:
```suggestion
        const onInput = debounce(fetchData, 100);
```
We can shorten this time, I tested it w/100 and wasn't able to reproduce the bug but test it yourself and make sure.

**Review by donnyquixotic — CHANGES_REQUESTED** [review]

**Review by donnyquixotic — APPROVED** [review]
