### PR TITLE
Increases row height for memo to be visible

### LINKED ISSUE #761: Action info gets cropped when it has two lines of info
**Describe the bug**
As can be seen in the screenshot, the height of the row is not enough to hold two lines of the info on each action.

**To Reproduce**
1. Go to [this account page](https://explorer.telos.net/account/viterbotelos)
3. Scroll down to see the last actions
4. See the error described. The info of the action does not fit in the height space.

**Expected behavior**
No cropping of the text is expected when it has exactly two lines.

**Screenshots**

image

### PR DESCRIPTION
**Pull request by karynemayer**
# Fixes #761

## Description
Increases the row height on the transaction table so the memo is visible:

before:
Screenshot 2023-10-03 at 12 11 32

now:
Screenshot 2023-10-03 at 12 10 38

## Checklist:

-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have cleaned up the code in the areas my change touches
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have removed any unnecessary console messages
-   [ ] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [ ] I have tested for mobile functionality and responsiveness
-   [ ] I have added appropriate test coverage

### CODE REVIEW

**Review by jaegerfe — DISMISSED** [review]

File: src/components/transaction/DataFormat.vue [hunk 1]
```diff
@@ -29,7 +29,7 @@ export default defineComponent({
         const transferData = computed(() => actionData.value as TransferData);
         const clientHeight = computed(() => dataBox.value?.clientHeight ?? 0);
         let currentData = ref<string | unknown>(null);
-        const maxHeight = 57; // the maximum row height
+        const maxHeight = 77; // the maximum row height
```
Comment (Viterbo) [inline src/components/transaction/DataFormat.vue:32]:
```suggestion
        const maxHeight = 65; // the maximum row height
```

I would suggest changing the maxHeight to 65 since it if is too big it will cause this not desired effect
image

**Review by Viterbo — CHANGES_REQUESTED** [review]
