### PR TITLE
218 bug sign transaction ux

### LINKED ISSUE #218: BUG - sign transaction
**Describe the bug**
 the flow to sign a transaction seems off: I have to login every time before I sign, so 2 interactions with Anchor instead of just one.  This  results in 2 tabs open with just a “Launch Anchor” button on them, one of which was the explorer.  So I have to close the 2nd tab and click back on the first tab.

### PR DESCRIPTION
**Pull request by WikusKriek**
# Pull Request Template

## Description

Fixed signing flow and double login issues with signer. Also added cleos signer support.

Fixes #218 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

File: src/boot/ual.ts [hunk 1]
```diff
@@ -20,8 +24,132 @@ export default boot(({ app }) => {
...
+                color: 'red-8',
+                textColor: 'white',
+                message: 'Could not copy',
+                timeout: 1000
+              });
+            });
+        })
+        .onCancel(() => {
+          //console.log('>>>> Cancel');
+        })
```
Comment (donnyquixotic) [inline src/boot/ual.ts:139]: did you mean to `Throw 'Canceled!'` here? Can also remove commented out code

**Review by donnyquixotic — CHANGES_REQUESTED** [review]

File: src/boot/ual.ts (hunk 1 above)
Comment (WikusKriek) [reply src/boot/ual.ts:134]: Okay made the changes, also changed the spelling to American english XD @donnyquixotic

**Review by donnyquixotic — APPROVED** [review]
