### PR TITLE
Fix proposal execute button - fixing the math for isApproved

### LINKED ISSUE #835: Execute MSIG tx by non MSIG Accounts on Block Explorer
On MSIG tx, allow any account to execute it, currently only MSIG accounts can it seems.

Refinement:
The problem is that the condition isApproved is currently calculated wrong.

Let's call this first case a private proposal in which only private accounts are part of the requested approvals. In this case the `isApproved `property should be taking into account the amount of requested versus approved and they have to be the same.
http://localhost:8080/proposal/voqbcbtcll3j
image

Let's call this other case a public proposal where the approval of BPs where solicited. In this other different case, we need at least (2/3+1) of the total amount of active BPs having approved the proposal. Only in that case, the proposal is approved.
http://localhost:8080/proposal/aprfeeburn
image

### PR DESCRIPTION
**Pull request by Viterbo**
# Fixes #835, #841

## Description
This PR repairs the login behind the condition of isApproved. it also fixes a problem with the .env when it's not present (fresh repo clone).

## Test scenarios
- Go to this proposal link (I don't have a Mainnet deployment to show)
- Get logged in (use a non-BP account)
- See that it already shows an execution button

or run it locally with this code:
```bash
# clone the repo if you don'e have it
git clone https://github.com/telosnetwork/open-block-explorer.git
cd open-block-explorer
# run the correct branch
git fetch origin
git checkout 835-execute-msig-tx-by-non-msig-accounts-on-block-explorer
yarn
yarn dev
```

make sure you have the file `.env` with this code:
```
APP_NAME=OBE
CHAIN_NAME=telos
```

then visit http://localhost:8080/proposal/aprfeeburn

image

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages
-   [x] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [x] I have tested for mobile functionality and responsiveness
-   [x] I have added appropriate test coverage
-   [x] I have updated relevant documentation and/or opened a separate issue to cover the updates (Issue URL: )

### CODE REVIEW

File: src/pages/ProposalItem.vue [hunk 1]
```diff
@@ -302,6 +295,22 @@ export default defineComponent({
...
+            );
+
+            if (activeProducers.value.length === 0) {
+                // No BPs are involved in the proposal, so we need to 100% of the requested approvals
+                isApproved.value = proposal.provided_approvals.length === totalRequestedApprovals;
+            } else {
+                // If BPs are involved, we need 2/3 (+1) of the BPs to approve the proposal
+                const approval = (activeProducers.value.length * 2 / 3) + 1;
+                isApproved.value = activeProducersApproved.value.length >= Math.floor(approval);
+            }
```
Comment (Viterbo) [inline src/pages/ProposalItem.vue:312]: This is the more important part.
This should be checked by @jbuice

File: src/config/ConfigManager.ts [hunk 2]
```diff
@@ -96,13 +96,23 @@ export default class ConfigManager {
...
-        return this.testnets.find(c => c.getName() === chainName);
+        if (fromMainnet) {
+            return fromMainnet;
+        } else {
+            if (typeof chainName === 'string') {
+                throw new Error(`Chain '${chainName}' not found`);
+            } else {
+                throw new Error('CHAIN_NAME env variable not found');
+            }
+        }
```
Comment (Viterbo) [inline src/config/ConfigManager.ts:116]: This fifes https://github.com/telosnetwork/open-block-explorer/issues/841

**Review by pmjanus — APPROVED** [review]
