### PR TITLE
139 bug resource crunch colors

### LINKED ISSUE #139: BUG - Resource crunch colors
This wasn't well defined, but in the original designs, as resources reach their max, the color should change. I'm open to suggestion how to tackle this, but I think that anything above 80% should be red.

image

### PR DESCRIPTION
**Pull request by WikusKriek**
# Pull Request Template

## Description

Anything above 80 is red rest stays white.
image

Fixes #139

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

File: src/store/chain/actions.ts [hunk 1]
```diff
@@ -17,11 +17,37 @@ export const actions: ActionTree<ChainStateInterface, StateInterface> = {
...
+        );
+        if (bp) {
+          try {
+            return {
+              ...data,
+              name: bp.org.candidate_name,
+              location: bp.org.location.name
+            };
+          } catch (error) {
+            return data;
```
Comment (DonaldPeat) [inline src/store/chain/actions.ts:38]: return the `error`  (with `data` )  here?

**Review by DonaldPeat — CHANGES_REQUESTED** [review]
